### PR TITLE
 Local Coffee Shops

### PR DESCRIPTION
**Pull request by CoryKelly**
- Added Nashville Local Coffee Shops
- Updated Name of coffee shop

### CODE REVIEW

**Comment by matthamil** [comment]
Awesome @CoryKelly ! :tada: It looks like your editor may have created some relics in a `.history` directory which also got committed--can you remove these and commit?

```bash
git rm -r --cached .history
```

should remove the directory from git but keep it on your filesystem. Alternative, don't include the `--cached` flag if you want to also nuke it from your filesystem and commit again. Or, you can just delete the files and commit :)

**Comment by matthamil** [comment]
Another alternative--feel free to create a `.gitignore` at the root of the repo and include `.history` in that. (You'll still need to remove the .history from git before pushing)

**Comment by matthamil** [comment]
Huzzah! Awesome! Thank you!

**Comment by CoryKelly** [comment]
Thanks, doing that now.

**Pull request merged**
